#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("BookingSystem.Resource", IsApplication=true)]

namespace BookingSystem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_in_right = global::BookingSystem.Resource.Animation.slide_in_right;
			global::Xamarin.Auth._MobileServices.Resource.Animation.slide_out_left = global::BookingSystem.Resource.Animation.slide_out_left;
			global::Xamarin.Auth._MobileServices.Resource.Drawable.ic_arrow_back = global::BookingSystem.Resource.Drawable.ic_arrow_back;
			global::Xamarin.Auth._MobileServices.Resource.Id.webview = global::BookingSystem.Resource.Id.webview;
			global::Xamarin.Auth._MobileServices.Resource.Layout.activity_webview = global::BookingSystem.Resource.Layout.activity_webview;
			global::Xamarin.Auth._MobileServices.Resource.String.ApplicationName = global::BookingSystem.Resource.String.ApplicationName;
			global::Xamarin.Auth._MobileServices.Resource.String.Hello = global::BookingSystem.Resource.String.Hello;
			global::Xamarin.Auth._MobileServices.Resource.String.title_activity_webview = global::BookingSystem.Resource.String.title_activity_webview;
			global::PCLCrypto.Resource.String.ApplicationName = global::BookingSystem.Resource.String.ApplicationName;
			global::PCLCrypto.Resource.String.Hello = global::BookingSystem.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_right = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_left = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070002
			public const int genSpinner = 2131165186;
			
			// aapt resource value: 0x7f070000
			public const int leagueSpinner = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int teamSpinner = 2131165185;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int bgColor = 2131099648;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int ic_arrow_back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_logo = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int logout = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int soccerBall = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a0013
			public const int btnCont = 2131361811;
			
			// aapt resource value: 0x7f0a0017
			public const int btnCreateTeam = 2131361815;
			
			// aapt resource value: 0x7f0a000a
			public const int btnLeague = 2131361802;
			
			// aapt resource value: 0x7f0a0006
			public const int btnLogin = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int btnRegister = 2131361799;
			
			// aapt resource value: 0x7f0a0009
			public const int btnSchedule = 2131361801;
			
			// aapt resource value: 0x7f0a000c
			public const int btnTeamManage = 2131361804;
			
			// aapt resource value: 0x7f0a001c
			public const int btnTeamReq = 2131361820;
			
			// aapt resource value: 0x7f0a000b
			public const int btnTeams = 2131361803;
			
			// aapt resource value: 0x7f0a0012
			public const int datePicker = 2131361810;
			
			// aapt resource value: 0x7f0a0004
			public const int etEmail = 2131361796;
			
			// aapt resource value: 0x7f0a0005
			public const int etPass = 2131361797;
			
			// aapt resource value: 0x7f0a000e
			public const int firstName = 2131361806;
			
			// aapt resource value: 0x7f0a0008
			public const int imageView1 = 2131361800;
			
			// aapt resource value: 0x7f0a000f
			public const int lastName = 2131361807;
			
			// aapt resource value: 0x7f0a0003
			public const int lgHeader1 = 2131361795;
			
			// aapt resource value: 0x7f0a001b
			public const int lgRow1 = 2131361819;
			
			// aapt resource value: 0x7f0a001d
			public const int logout = 2131361821;
			
			// aapt resource value: 0x7f0a0010
			public const int mobNo = 2131361808;
			
			// aapt resource value: 0x7f0a0015
			public const int schedHeader1 = 2131361813;
			
			// aapt resource value: 0x7f0a0011
			public const int spnGender = 2131361809;
			
			// aapt resource value: 0x7f0a0001
			public const int spnLeague = 2131361793;
			
			// aapt resource value: 0x7f0a0018
			public const int spnTeam = 2131361816;
			
			// aapt resource value: 0x7f0a0002
			public const int tabLayLeague = 2131361794;
			
			// aapt resource value: 0x7f0a0019
			public const int tabLayRequests = 2131361817;
			
			// aapt resource value: 0x7f0a0014
			public const int tabLaySched = 2131361812;
			
			// aapt resource value: 0x7f0a001a
			public const int tabLayTeam = 2131361818;
			
			// aapt resource value: 0x7f0a0016
			public const int teamName = 2131361814;
			
			// aapt resource value: 0x7f0a000d
			public const int txtPrompt = 2131361805;
			
			// aapt resource value: 0x7f0a0000
			public const int webview = 2131361792;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_webview = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LeagueView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainMenu = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int RegView = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int ScheduleView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int TeamCreateView = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TeamManageView = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TeamView = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f090000
			public const int menu = 2131296256;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int leaguePrompt = 2131034115;
			
			// aapt resource value: 0x7f050005
			public const int managePrompt = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int teamPrompt = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int title_activity_webview = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int customTheme = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int customThemeNoBar = 2131230721;
			
			// aapt resource value: 0x7f080004
			public const int datePickerStyle = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int header = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int strongText = 2131230722;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
